# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, Qt


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(232, 189)
        # 固定窗口大小
        Form.setFixedSize(Form.size())
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 211, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnDown = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnDown.setObjectName("btnDown")
        self.verticalLayout.addWidget(self.btnDown)
        self.btnReWriter = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnReWriter.setObjectName("btnReWriter")
        self.verticalLayout.addWidget(self.btnReWriter)
        self.btnWordCorrect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnWordCorrect.setObjectName("btnWordCorrect")
        self.verticalLayout.addWidget(self.btnWordCorrect)
        self.btnGenerateSrc = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnGenerateSrc.setObjectName("btnGenerateSrc")
        self.verticalLayout.addWidget(self.btnGenerateSrc)
        self.btnSrcCorrect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnSrcCorrect.setObjectName("btnSrcCorrect")
        self.verticalLayout.addWidget(self.btnSrcCorrect)
        self.retranslateUi(Form)

        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "推文助手"))
        self.btnDown.setText(_translate("Form", "下载素材"))
        self.btnReWriter.setText(_translate("Form", "Chatgpt重写文案"))
        self.btnWordCorrect.setText(_translate("Form", "Word文档格式修复"))
        self.btnGenerateSrc.setText(_translate("Form", "剪映-生成字幕与配音"))
        self.btnSrcCorrect.setText(_translate("Form", "字幕格式纠正"))
